### ISSUE TITLE
Add secret to github repo to allow running lamin login

### ISSUE THREAD

**Issue by rcannood** [laminlabs/laminr#17]
The CI needs a secret to be able to log into lamin.ai to:

* Run unit tests #7 
* Generate documentation #13 

@falexwolf Could you add a secret to this repository or give me permissions to do so myself?

**Comment by falexwolf** [comment]
I posted the info on Slack.

For redundancy :)

```
jobs:
  test:
    env:
      LAMIN_API_KEY_TESTUSER1: ${{ secrets.LAMIN_API_KEY_TESTUSER1 }}
    steps:
      - uses: actions/setup-python@v5
      - run: pip install lamin-cli
      - run: lamin login
```
